<?php
$CONFIG = array (
  'updatechecker' => false,
  'instanceid' => 'oc2t9y66hlez',
  'passwordsalt' => 'gdDQina5ZL16BbsdpmZKekC3JhFOda',
  'secret' => 'LLWxreHNl3zfYfRAcxhYDN1L1H/WErkdcyBTjX0nJV3PuFZt',
  'trusted_domains' => 
  array (
    0 => 'server',
    1 => '{{ SRV_IP }}',
    2 => 'nextcloud',
    3 => '{{ EXTERNAL_IP }}',
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '19.0.1.1',
  'overwrite.cli.url' => 'http://{{ SRV_IP }}/nextcloud',
  'dbname' => '{{ DB_NAME }}',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => '{{ DB_USER }}',
  'dbpassword' => '{{ DB_PWD }}',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'ldapProviderFactory' => 'OCA\\User_LDAP\\LDAPProviderFactory',
  'forcessl' => true,
  'theme' => 'lliurex',
  'default_language' => '{{ DEFAULT_LOCALE }}', 
);
